### ISSUE TITLE
genbox broken with gfortran-8.1

### ISSUE THREAD

**Issue by jedbrown** [Nek5000/Nek5000#517]
```
Running genbox ...
At line 131 of file genbox.f (unit = 5, file = 'stdin')
Fortran runtime error: Missing initial left parenthesis in format

^

Error termination. Backtrace:
#0  0x7ff5dbff9fe7 in data_transfer_init
        at /build/gcc/src/gcc/libgfortran/io/transfer.c:2794
#1  0x55e6831d40e6 in ???
#2  0x55e6831e1a93 in ???
#3  0x7ff5db24d06a in ???
#4  0x55e6831c70c9 in ???
#5  0xffffffffffffffff in ???
 input file name:
```

Cc: @thilinarmtb

**Comment by jedbrown** [comment]
My apologies. This seems to have been caused by stale object files, but I'm not going back to reproduce why they were not cleaned.
